USE [master]
GO

/****** Object:  Database [BusesDataManagement]    Script Date: 6/1/2024 2:24:18 PM ******/
CREATE DATABASE [BusesDataManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BusesDataManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BusesDataManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BusesDataManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BusesDataManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BusesDataManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BusesDataManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BusesDataManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BusesDataManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BusesDataManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BusesDataManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [BusesDataManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BusesDataManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BusesDataManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BusesDataManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BusesDataManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BusesDataManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BusesDataManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BusesDataManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BusesDataManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BusesDataManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BusesDataManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BusesDataManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BusesDataManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BusesDataManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BusesDataManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BusesDataManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BusesDataManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BusesDataManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [BusesDataManagement] SET  MULTI_USER 
GO

ALTER DATABASE [BusesDataManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BusesDataManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BusesDataManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BusesDataManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BusesDataManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BusesDataManagement] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BusesDataManagement] SET QUERY_STORE = ON
GO

ALTER DATABASE [BusesDataManagement] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BusesDataManagement] SET  READ_WRITE 
GO

USE [BusesDataManagement]
GO

/****** Object:  Table [dbo].[Buses]    Script Date: 6/1/2024 2:24:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Buses](
	[BusNumber] [varchar](50) NOT NULL,
	[Description] [varchar](500) NULL,
 CONSTRAINT [PK_Buses] PRIMARY KEY CLUSTERED 
(
	[BusNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [BusesDataManagement]
GO

/****** Object:  Table [dbo].[BusRoutes]    Script Date: 6/1/2024 2:24:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BusRoutes](
	[BusStationNumber] [int] IDENTITY(1,1) NOT NULL,
	[BusNumber] [varchar](50) NOT NULL,
	[RouteNumber] [int] NOT NULL,
	[StationName] [varchar](500) NOT NULL,
	[StationDescription] [varchar](500) NULL,
 CONSTRAINT [PK_BusRoutes] PRIMARY KEY CLUSTERED 
(
	[BusStationNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [BusesDataManagement]
GO

/****** Object:  Table [dbo].[TimeTable]    Script Date: 6/1/2024 2:25:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TimeTable](
	[StationNumber] [int] NOT NULL,
	[Route1] [varchar](50) NULL,
	[Route2] [varchar](50) NULL,
	[Route3] [varchar](50) NULL,
	[Route4] [varchar](50) NULL,
	[Route5] [varchar](50) NULL,
	[Route6] [varchar](50) NULL,
	[Route7] [varchar](50) NULL,
	[Route8] [varchar](50) NULL,
 CONSTRAINT [PK_TimeTable] PRIMARY KEY CLUSTERED 
(
	[StationNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TimeTable]  WITH CHECK ADD  CONSTRAINT [FK_TimeTable_BusRoutes] FOREIGN KEY([StationNumber])
REFERENCES [dbo].[BusRoutes] ([BusStationNumber])
GO

ALTER TABLE [dbo].[TimeTable] CHECK CONSTRAINT [FK_TimeTable_BusRoutes]
GO

USE [BusesDataManagement]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 6/1/2024 2:26:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Username] [varchar](50) NOT NULL,
	[Password] [varchar](20) NOT NULL,
	[Role] [varchar](10) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

